services:
  - type: web
    name: okx-trading-bot
    env: python
    region: frankfurt  # можно поменять на другой при желании
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
